apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: vipam.everoute.io
webhooks:
  - admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    clientConfig:
      # CaBundle must set as the ca for secret everoute-controller-tls.
      caBundle:
      service:
        name: ippool-controller
        path: /validate-ipam-everoute-io-v1alpha1-ippool
        port: 9443
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    name: vipam.everoute.io
    rules:
      - apiGroups:
          - ipam.everoute.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - ippools
