name: unit-test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: [self-hosted, pod]
    steps:
     - uses: actions/checkout@v3

     - uses: andstor/file-existence-action@v2
       id: check_files
       with:
         files: "go.mod"

     - name: run unit-test with docker
       if: steps.check_files.outputs.files_exists == 'true'
       run: make docker-test

     - uses: codecov/codecov-action@v2
       if: steps.check_files.outputs.files_exists == 'true'
       with:
         files: ./coverage.out
         token: ${{ secrets.CODECOV_TOKEN }}
